<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <AssemblyName>Engine.Content.FmtCollada</AssemblyName>
    <RootNamespace>Engine.Content.FmtCollada</RootNamespace>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Engine.Content.FmtCollada.snk</AssemblyOriginatorKeyFile>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <SonarQubeTestProject>False</SonarQubeTestProject>
  </PropertyGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Runtime.Loader.UseRidGraph" Value="true" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\Engine.csproj" />
  </ItemGroup>

</Project>