name: Build dev branch

on:
  push:
    branches: [ dev ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
jobs:
  build:
    name: "Build"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
      
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: dotnet restore ${{env.SOLUTION_FILE_PATH}}

      - name: Sonar begin
        working-directory: ${{env.GITHUB_WORKSPACE}}
        shell: powershell
        run: .\.sonar\scanner\dotnet-sonarscanner begin /k:"Selinux24_Skirmish_dev" /o:"selinux24-github" /d:sonar.token="${{secrets.SONAR_TOKEN}}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths="**\TestResults\**\*.xml" /d:sonar.coverage.exclusions=".\Tests\**"
        
      - name: Build
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
        
      - name: VSTest
        run: vstest.console.exe /Platform:x64 /Enablecodecoverage /Collect:"Code Coverage;Format=Xml" /ResultsDirectory:".\TestResults" .\Tests\EngineTests\bin\Release\net7.0\EngineTests.dll .\Tests\Engine.PhysicsTests\bin\Release\net7.0\Engine.PhysicsTests.dll
        
      - name: Sonar end
        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{secrets.SONAR_TOKEN}}"
